### ISSUE TITLE
Project does not run

### ISSUE THREAD

**Issue by mittalharsh54** [NordicSemiconductor/nRF-Logger-API#1]
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_51\bin\java.exe'' finished with non-zero exit value 2
This error while running the project

**Comment by philips77** [comment]
Hi, did you add the jar the same way it's added in the nRF Toolbox application? 
https://github.com/NordicSemiconductor/Android-nRF-Toolbox
It works for me there.

**Comment by mittalharsh54** [comment]
Hi,
Yes I have added it but unfortunately it is not working for me.
I am stuck there from 2  days as I want to get a log file which shows the
beacons scanned in a minute in my beacon app, So i preffered your
 project.Please help me if you can. Anything will be appreciated.
Thanks

HARSH NIRANJAN MITTAL

**Comment by philips77** [comment]
Do you use Android Studio or Eclipse?
For Eclipse you just need to copy the jar to *libs* folder.
In the AS you should do the following:
1. copy the lib to your components folder to libs folder, for example MyProject/app/libs
2. add ```compile files('libs/nrf-logger-v2.0.jar')``` to build.gradle file in your app folder.

I will publish the library on jcenter soon to make the process easier.

**Comment by philips77** [comment]
Hi, I just published the lib on jcenter. It should be (hopefully) ready in couple of hours. I'll let you know and update the main page how to add dependency..

**Comment by mittalharsh54** [comment]
Hi, ok thanks for your so valuable reply and yes i will be waiting for the updated app. :)

**Comment by philips77** [comment]
Hi, sorry for delay, but it takes some time to publish on jcentral.
It's not complete and you can add:

```compile 'no.nordicsemi.android:log:2.0.0'```

to your component's *build.gradle* file.

**Comment by philips77** [comment]
Please, remember also to add the permission to AndroidManifest.xml:

```<uses-permission android:name="no.nordicsemi.android.LOG"/>```

**Comment by mittalharsh54** [comment]
Yh ok no problem.!
