### ISSUE TITLE
Which license it is?

### ISSUE THREAD

**Issue by thejeshgn** [NordicSemiconductor/nRF-Logger-API#2]
Dear @philips77 

At https://mvnrepository.com/artifact/no.nordicsemi.android/log/2.0.0  it says BSD3

and the repo has MIT.

1. Which license it is?
2. How can I get the source code? Is it the one inside jar files?

**Comment by philips77** [comment]
I've just changed the license to BSD-3-clause in the repo. Sorry, all our mobile source should have this one.
Yes, the source code is either in the jar, or on Maven/jcenter.
If it's not enough I can publish it the normal way. This repo was just created before we switched to Android Studio, long time ago...

**Comment by thejeshgn** [comment]
Thanks @philips77 

It will be great if we have source code as part of this project. May be inside a source folder.

**Comment by philips77** [comment]
Hi, I've updated the lib to 2.1.0 and shared sources here. Bulk log entries insert has been added.
