### ISSUE TITLE
Logcat session

### ISSUE THREAD

**Issue by bojanpotocnik** [NordicSemiconductor/nRF-Logger-API#4]
I am wondering if/how is it possible to configure the Logger to use Logcat instead?

Currently 
`final LogSession logSession = Logger.newSession(getApplication(), ...);` 
is used to generate a new logging session, which is then used in many
`Logger.log(mLogSession, level, message);`
statements across the application. 
There comes my question - in early development Logcat is still the most convenient logging method to use. However I am wondering if there is more elegant way to simply switch Logger to using Logcat instead of replacing all `Logger.log(...);` calls with `Log.v()/Log.d(), ...`?

Thank you

**Comment by philips77** [comment]
I'd recommend using Timber. There you may implement a Tree that will log with nRF Logger and switch to it from DebugTree later. There's no Billy in integration.

**Comment by bonebizz21** [comment]
Thanks

**Comment by bonebizz21** [comment]
Debug tree

**Comment by bonebizz21** [comment]
Logger.log(mLogSession, level, message);

**Comment by philips77** [comment]
Hi, I've added Timber integration now. Import `no.nordicsemi.android:log-timber:2.1.3` dependency and plant **nRFLoggerTree** and **LogcatTree** to get logs on both.
