### ISSUE TITLE
Proguard configuration not exported

### ISSUE THREAD

**Issue by al-broco** [NordicSemiconductor/nRF-Logger-API#6]
Lib documentation states:

> If you use proguard, add the following line to your proguard rules: -keep class no.nordicsemi.android.log.** { *; }

This manual step is easy to forget (especially if the logger is a transient dependency) and can be automated. Reference: https://developer.android.com/studio/projects/android-library, the section "A library module may include its own ProGuard configuration file".

In essence, change the build.gradle to say something like

````
    defaultConfig {
        consumerProguardFiles 'lib-proguard-rules.txt'
    }
````

And include the rule in the lib-proguard-rules.txt file.

**Comment by philips77** [comment]
Fixed in 2.1.2
